##### 
# Core Site Settings
#####

# baseURL: "#{hostname}#" # BaseURL of the website, used in RSS feeds and site rendering
buildFuture: true         # Include content with publishdate in the future
enableRobotsTXT: true     # Generate a customized robots.txt
languageCode: "en-gb"     # Used as part of the XML generation
title: "Chris Reddington" # Title of the website

module:
  imports:
    path: "github.com/chrisreddington/cv"
  mounts:
    - source: "node_modules/bootstrap/js/dist"
      target: "assets/js"
    - source: "node_modules/@popperjs/core/dist/umd"
      target: "assets/js"
    - source: "node_modules/jquery/dist"
      target: "assets/js"
    - source: "node_modules/fuse.js/dist"
      target: "assets/js"
    - source: "node_modules/bootstrap/scss"
      target: "assets/sass/bootstrap"
    - source: "./node_modules/@fortawesome/fontawesome-free/scss"
      target: "assets/sass/fontawesome"
    - source: "./node_modules/@fortawesome/fontawesome-free/webfonts"
      target: "static/webfonts"
    - source: static
      target: static
    - source: assets
      target: assets

# Custom Parameters that drive the site's
# configuration. This includes custom
# functionality, such as comments,
# RSS feed options, etc.
params:
  # Parameters relating to site content
  content:
    # Configuration information for the site itself. Some of 
    # this will also be used within RSS feeds, etc.
    site:
      author: "Chris Reddington" # Owner of the site
      copyright:
        additional_information: "[Hugo Creator](https://github.com/cloudwithchris/Hugo-Creator) theme created by [Chris Reddington](https://www.cloudwithchris.com)" # I'd greatly appreciate if you would keep this in!
        established: "2020" # Year established (i.e. start year in a range)
        notice: "[Chris Reddington](https://www.christianreddington.co.uk). Proudly running using [Hugo](https://gohugo.io/)." # Your Copyright
      description: "Exploring Cloud concepts with Chris Reddington (Welsh Tech Geek, Cloud Advocate, Musical Theatre Enthusiast and Improving Improviser!). We will regularly invite guests to talk about their experiences with the cloud and hear about some of the lessons learned around their cloud journey. Cloud with Chris is a community-driven personal podcast. Content from episodes do not represent the views of any company or organisation." # This is used in site metadata and RSS feeds.
      #####
      # Keywords
      #####
      #
      # Keywords are used for site metadata tags.
      # These are concatenated with tags from pages.
      #
      keywords:
        - cloud
        - azure
      language_name: "English"
      logo: "images/chris.jpg" # Relative path to the site's logo
    social:
      discord: "9FJctHP9Zv"
      facebook: "CloudWithChris"
      github: "CloudWithChris"
      linkedin: "chrisreddington"
      tiktok: "cloudwithchris"
      twitter: "CloudWithChris"
      twitter_domain: "cloudwithchris.com" # This domain shows in twitter cards as "View on `twitter_domain`"
      youtube: "CloudWithChris"
  # Parameters relating to site features and functionality
  features:
    # Settings related to analytics
    analytics:
      googleAnalytics: "UA-185951371-1"       # Google Analytics ID
      microsoftClarity: "a32lpsz3a1"
  security:
    # If all CSP properties are empty strings, then
    # the CSP section will not be rendered. If at least 1
    # contains a string, then it will be rendered.
    csp:
      scriptsrc: ""
      imgsrc: ""
      connectsrc: ""
      framesrc: ""
      objectsrc: ""
# Privacy options built in to hugo. The hugo docs explain how to configure this to align with GDPR, so please make sure to ensure this is configured as appropriate for your deployment.
# -
# https://gohugo.io/about/hugo-and-gdpr/
privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false
# Taxonomies in hugo are used to easily identify content that belongs
# to a given piece of metadata. This is particularly useful for tags,
# or pieces of content that appear in a series. All taxonomies used within
# the theme are configured below.
taxonomies:
  tag: "tags"