##### 
# Core Site Settings
#####

# baseURL: "#{hostname}#" # BaseURL of the website, used in RSS feeds and site rendering
buildFuture: true         # Include content with publishdate in the future
enableRobotsTXT: true     # Generate a customized robots.txt
languageCode: "en-gb"     # Used as part of the XML generation
theme: "cv"     # Name of the theme. Don't change this from hugo-creator.
title: "Cloud With Chris" # Title of the website

#####
# This is required to render the raw HTML on the
# about us page.
#####
markup:
  goldmark:
    renderer:
      unsafe: true

module:
  mounts:
    - source: "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target: "assets/js/bootstrap.bundle.min.js"
    - source: "node_modules/bootstrap/scss"
      target: "assets/sass/bootstrap"
    - source: "./node_modules/@fortawesome/fontawesome-free/scss"
      target: "assets/sass/fontawesome"
    - source: "./node_modules/@fortawesome/fontawesome-free/webfonts"
      target: "static/webfonts"
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes

# This enables the search functionality
# to work, as it searches over the json file.
# In effect, this allows the layouts/index.json
# file to be rendered.
outputs:
  home:
    - "HTML"
    - "RSS"

# Custom Parameters that drive the site's
# configuration. This includes custom
# functionality, such as comments,
# RSS feed options, etc.
params:
  # Parameters relating to site content
  content:
    # Configuration information for the site itself. Some of 
    # this will also be used within RSS feeds, etc.
    site:
      author: "Chris Reddington" # Owner of the site
      copyright:
        additional_information: "[Hugo Creator](https://github.com/cloudwithchris/Hugo-Creator) theme created by [Chris Reddington](https://www.cloudwithchris.com)" # I'd greatly appreciate if you would keep this in!
        established: "2020" # Year established (i.e. start year in a range)
        notice: "[Chris Reddington](https://www.christianreddington.co.uk). Proudly running using [Hugo](https://gohugo.io/)." # Your Copyright
      description: "Exploring Cloud concepts with Chris Reddington (Welsh Tech Geek, Cloud Advocate, Musical Theatre Enthusiast and Improving Improviser!). We will regularly invite guests to talk about their experiences with the cloud and hear about some of the lessons learned around their cloud journey. Cloud with Chris is a community-driven personal podcast. Content from episodes do not represent the views of any company or organisation." # This is used in site metadata and RSS feeds.
      #####
      # Keywords
      #####
      #
      # Keywords are used for site metadata tags.
      # These are concatenated with tags from pages.
      #
      keywords:
        - cloud
        - azure
        - gcp
        - aws
        - chris reddington
        - cloud tutorials
        - cloud design patterns
        - devops how to
        - how to deploy using github actions
        - how to design for the cloud
        - cloud architecture
        - azure architecture center
        - google cloud platform
        - amazon web services
        - christian reddington
        - github
        - github actions
        - github discussions
        - microsoft
        - github issues
        - amazon
        - google
        - SLO
        - SLA
        - RTO
        - RPO
        - non-functional requirements
        - functional requirements
        - requirements
        - cost management
        - cloud governance
        - cost control
        - resource governance
        - cloud recommended practices
        - cloud best practices
        - learn cloud
        - learn Azure
        - Microsoft Azure
        - how to get started with azure
        - how to keep up to date with azure
        - technology podcast
        - technology vlog
        - azure vlog
        - azure podcast
        - cloud podcast
        - cloud vlog
        - cloud content
        - azure content
        - github content
        - github podcast
        - github vlog
        - azure design patterns
        - kubernetes
        - azure kubernetes service
        - azure app service
        - platform as a service
        - infrastructure as a service
        - software as a service
        - cloud gaming
        - gaming
        - game server
        - application development
        - software development
        - devops
        - liveops
        - Continuous Integration
        - Continuous Deployment
        - azure updates
        - azure blog
        - cloud blog
        - github blog
        - devops blog
        - meetup speaker
        - technology speaker
        - keynote speaker
        - technology keynote
        - conference speaker
        - technology conference speaker
        - cloud gaming technology
        - how cloud is influencing gaming
        - cloud drops
        - architecting for the cloud one pattern at a time
        - tales from the real world
        - cloud gaming notes
        - tech roundup
        - static websites
        - hugo
        - hugo on azure
        - static content
        - azure static web apps
        - logic apps
        - iPaas
        - serverless
        - Azure Functions
        - key vault
        - azure key vault
        - CosmosDB
        - Git
        - version control
        - .net
        - dotnet
        - terraform
        - arm templates
        - bicep
        - cloud monitoring
        - azure monitor
        - azure governance
        - compute resource consolidation
        - queueing
        - messaging
        - publish subscriber patterns
        - priority queue patterns
        - pipes and filters pattern
        - geode pattern
        - health endpoint monitoring pattern
        - gatekeeper pattern
        - valet key pattern
        - JAMStack
        - static content hosting pattern
        - github codespaces
        - anti-corruption layer pattern
        - gateway aggregation pattern
        - gateway routing pattern
        - event sourcing pattern
        - cqrs pattern
        - command query responsibility segregation pattern
        - throttling pattern
        - retry pattern
        - circuit breaker pattern
        - backends for frontends pattern
        - sharding pattern
        - index table pattern
        - deployment stamps pattern
        - cloud security
        - devsecops
      language_name: "English"
      logo: "/img/Cloud.png" # Relative path to the site's logo
      media_prefix: "https://podcasts.cloudwithchris.com/" # Media_Prefix is used when referencing podcast audio files. The media files in individual episodes will be concatenated after the media_prefix above.
      ogimage: "/images/chris.jpg" # Used within RSS feeds.
    social:
      discord: "9FJctHP9Zv"
      facebook: "CloudWithChris"
      github: "CloudWithChris"
      linkedin: "chrisreddington"
      tiktok: "cloudwithchris"
      twitter: "CloudWithChris"
      twitter_domain: "cloudwithchris.com" # This domain shows in twitter cards as "View on `twitter_domain`"
      youtube: "CloudWithChris"
  # Parameters relating to site features and functionality
  features:
    # Settings relating to audio players embedded 
    # within the site.
    audio_player:
      use: "default"  # The options are default or podscribe
      podscribe:
        someconfig: "tbc"
    # Settings related to analytics
    analytics:
      googleAnalytics: "UA-185951371-1"       # Google Analytics ID
      microsoftClarity: "a32lpsz3a1"
  security:
    # If all CSP properties are empty strings, then
    # the CSP section will not be rendered. If at least 1
    # contains a string, then it will be rendered.
    csp:
      scriptsrc: ""
      imgsrc: ""
      connectsrc: ""
      framesrc: ""
      objectsrc: ""
# Privacy options built in to hugo. The hugo docs explain how to configure this to align with GDPR, so please make sure to ensure this is configured as appropriate for your deployment.
# -
# https://gohugo.io/about/hugo-and-gdpr/
privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false
# Taxonomies in hugo are used to easily identify content that belongs
# to a given piece of metadata. This is particularly useful for tags,
# or pieces of content that appear in a series. All taxonomies used within
# the theme are configured below.
taxonomies:
  tag: "tags"